{{- if and (eq .Values.global.mode "poc") (not .Values.nfs.provisioner.enabled) }}
# NFS PVC for POC when not using provisioner
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackbill-nfs-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: stackbill
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nfs.storage.size }}
{{- end }}

---
{{- if eq .Values.global.mode "poc" }}
# Shared storage PVC for StackBill data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackbill-shared-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: stackbill
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  {{- if (index .Values "nfs-provisioner").storageClass.name }}
  storageClassName: {{ (index .Values "nfs-provisioner").storageClass.name }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nfs.storage.size }}
{{- end }}
