{{- if .Values.rabbitmq.enabled }}
# RabbitMQ Definitions - Matches StackBill automated setup
# Based on: docs.stackbill.com/docs/deployment/installing-stackbill-components/installing-rabbitmq
# The application will create queues/exchanges as needed
apiVersion: v1
kind: Secret
metadata:
  name: stackbill-rabbitmq-definitions
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: stackbill
    app.kubernetes.io/component: rabbitmq-config
type: Opaque
stringData:
  load_definition.json: |
    {
      "rabbit_version": "3.13.0",
      "users": [
        {
          "name": "{{ .Values.rabbitmq.auth.username }}",
          "password": "{{ .Values.rabbitmq.auth.password | default "changeme" }}",
          "tags": ["administrator"]
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "{{ .Values.rabbitmq.auth.username }}",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "topic_permissions": [
        {
          "user": "{{ .Values.rabbitmq.auth.username }}",
          "vhost": "/",
          "exchange": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "parameters": [],
      "global_parameters": [
        {
          "name": "cluster_name",
          "value": "stackbill-rabbitmq"
        }
      ],
      "policies": [],
      "queues": [],
      "exchanges": [],
      "bindings": []
    }
{{- end }}
