apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateways.name }}
  http:
  - match:
    - port: {{ .Values.virtualService.port }}
    route:
    - destination:
        host: {{ .Values.service.name }}
        port:
          number: {{ .Values.virtualService.port }}
  - match:
    - uri:
        prefix: /static/*
    rewrite:
        uri: /static
    route:
    - destination:
        host: {{ .Values.service.name }}
        port:
          number: {{ .Values.virtualService.port }}